application: carpoolnext
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /(.*\.(html))
  static_files: static/\1
  upload: static/(.*\.(html))
- url: /resources
  static_dir: static/resources
- url: /bootstrap
  static_dir: static/bootstrap
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
